# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.11.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build"
  lane :build do
    gradle(
      task: "assembleDebug",
      flavor: "testflavor",
      #build_type: "Release"
      properties: {
    "versionCode" => 100,
    "versionName" => "1.0.0",
    # ...
  }
    )
  end

  #desc "Beta Build to Hockey"
  #lane :beta do
  #  gradle(task: "assembleRelease")
  #  crashlytics
#
    # sh "your_script.sh"
    # You can also use other beta testing services here
#  end

#  desc "Deploy to Google Play"
#  lane :deploy do
#    gradle(task: "assembleRelease")
#    supply
#  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics
